name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Artifact version'
        required: true
        default: 'unknown'
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish robot code
        run: ./gradlew publish -P pubs.publishJson -P pubs.publishJava -P repos.external -P auth.user="Team172" -P auth.key=${{ secrets.REPSY_PASSWORD }} -P pubs.version=${{ github.event.inputs.version }}
